### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by thbl** [NKoonen/languageperdomain#2]
Just tried your module, but seams it dosent work on latest prestashop ? 
if i add 2 diffrent top level domains, i just get "ERR_TOO_MANY_REDIRECTS" in frontend 😕

**Comment by NKoonen** [comment]
The module works in the latest PS version too.
Is your second domain set as an alias?
Please check if you have Friendly URL Enabled, and redirect to canonical URL set to “No redirection”.
Also check your .htaccess if the settings are correct.

**Comment by thbl** [comment]
-Please check if you have Friendly URL Enabled, and redirect to canonical URL set to “No redirection”.
This helped thank you ! :)
