### ISSUE TITLE
Seams module dosen't work with google sitemap

### ISSUE THREAD

**Issue by thbl** [NKoonen/languageperdomain#3]
Have you tried gsitemap ? https://github.com/PrestaShop/gsitemap
seams the module dosent work at all when languageperdomain is enabled :(

**Comment by JoryHogeveen** [comment]
Please describe the incompatibility in full.

**Comment by thbl** [comment]
it will only generate the sitemap of the main language (correct tho)
secound langauge it fails to generate

**Comment by thbl** [comment]
etc. i have 2 domains
beta.3do.dk
beta.3do.eu

but sitemap output is this
https://beta.3do.eu/1_index_sitemap.xml

**Comment by thbl** [comment]
@JoryHogeveen @NKoonen  i tried a couple of different sitemap modules, but dosen't seam like any of them works with your module :(
do you know of any that works with this module ? pretty important for SEO i guess

**Comment by JoryHogeveen** [comment]
We did not check sitemap modules so you'll have to check and integrate yourself!
