### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS - PS 8.1.1

### ISSUE THREAD

**Issue by thbl** [NKoonen/languageperdomain#8]
Hi
After I installed this module on PS 8.1.1 I got "ERR_TOO_MANY_REDIRECTS"
And when I try to open BO, it redirects to the main domain and gives the error "ERR_TOO_MANY_REDIRECTS"

Would you happen to have any suggestions? :)

**Comment by JoryHogeveen** [comment]
Hi @thbl 

Did you setup your domains correctly? One thing that I can think of is constant redirects from www to non-www and back.

**Comment by Marco-online** [comment]
"ERR_TOO_MANY_REDIRECTS", direct after install plugin

Setup is jwilder/nginx-proxy to Presta container

checked:
- Friendly URL Enabled
- Redirect to canonical URL set to “No redirection”.

**Comment by OrionCodeDev** [comment]
any idea how to repair it for 8.1 +?

**Comment by NKoonen** [comment]
For us to debug ERR_TOO_MANY_REDIRECTS we would need more server settings.
Couple of things you could check:

- www to not www redirect (for all the domains)
- Custom htaccess lines from other modules
- Is the PS setting "redirect to canonical url" disabled
- Are all domains pointing to the correct hosting
- Your DNS settings for all the domains
